name: Matrix Demo

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        a: ["foo", "bar"]
        b: ["quiz", "qax"]

    steps:
      - name: Echo matrix pair
        run: |
          echo "Matrix pair: ${{ matrix.a }}/${{ matrix.b }}"
          echo "a=${{ matrix.a }}"
          echo "b=${{ matrix.b }}"

      - name: Conditional failure for bar/qax
        run: |
          if [[ "${{ matrix.a }}" == "bar" && "${{ matrix.b }}" == "qax" ]]; then
            echo "This is the bar/qax combination - failing as expected"
            exit 1
          else
            echo "This combination (${{ matrix.a }}/${{ matrix.b }}) should pass"
          fi

  # Summary job that succeeds only if all matrix jobs succeed
  # This provides a single status check for branch protection rules
  check:
    runs-on: ubuntu-latest
    needs: matrix-job
    if: always()
    steps:
      - name: Check matrix job results
        run: |
          echo "Checking matrix job results..."
          echo "Matrix job result: ${{ needs.matrix-job.result }}"
          if [[ "${{ needs.matrix-job.result }}" == "success" ]]; then
            echo "✅ All matrix jobs completed successfully!"
            exit 0
          else
            echo "❌ One or more matrix jobs failed"
            exit 1
          fi
